-- ============================================================
-- Stellaris Surveillance Gaming Drills Platform
-- Craps + Caribbean Stud Poker — Question Pool Expansion
--
-- Adds, per game: 30 payout questions (odds stated in the
-- question text) + 30 shared procedure questions = 120 total.
--
-- Run ONCE in the Supabase SQL Editor AFTER seed_craps_csp.sql.
-- (Applied to production 2026-07-21 — do not re-run.)
--
-- SOURCE MANUALS (public/resources/*.pdf)
--   • Craps dealer procedures            (Updated 06-10-2020)
--   • Caribbean Stud Poker procedures     (Updated 06-09-2020)
--
-- FORMAT
--   payout questions state the odds in the text, e.g.
--   "Player bought the 4 (pays 2:1). The shooter rolls a 4.
--    How much does the dealer pay?" — the drill shows a random
--   chip stack; validation: bet × ratio (±2¢). correct_answer
--   holds the ratio as a decimal string ('2' = 2:1, '1.5' = 3:2,
--   '1.8' = 9:5, '1.4' = 7:5).
--
--   procedure questions are SHARED (game_id = NULL,
--   is_procedure = TRUE) so they surface in any session and in
--   the Procedures practice tab, like roulette_procedure:
--     category = 'craps_procedure'
--     category = 'caribbean_stud_procedure'
--
-- Difficulty is balanced 10 easy / 10 medium / 10 hard per
-- 30-question block.
-- ============================================================


-- ============================================================
-- ============================================================
-- CRAPS — PAYOUT DRILLS (30)  — odds stated in the question
-- ============================================================
-- ============================================================

-- ─── Easy (difficulty 1) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player has a bet on the Pass Line (pays 1:1). The shooter throws a natural 7 on the come-out roll. How much does the dealer pay?',NULL,'1','Pass Line bets are flat bets paid at 1 to 1 — the payout equals the wager.','craps_line',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','The point is 6 and the shooter rolls a 6. Calculate the payout on the Pass Line flat bet (pays 1:1).',NULL,'1','When the point repeats before a 7, the Pass Line flat bet is paid even money (1:1).','craps_line',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player''s Come bet traveled to the 9 and the shooter rolls a 9. What does the flat Come bet pay (pays 1:1)?',NULL,'1','Come bets are flat bets paid at 1 to 1 when their number repeats before a 7.','craps_line',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player has a Don''t Pass bet (pays 1:1). The shooter throws a 3 on the come-out roll. How much does the dealer pay?',NULL,'1','A come-out 3 wins for the Don''t Pass, which is paid at odds of 1 to 1.','craps_line',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Seven-out — the shooter misses the point. Calculate the payout on the Don''t Come bet behind the 5 (pays 1:1).',NULL,'1','A winning Don''t Come bet is paid at 1 to 1 when the seven appears before the number.','craps_line',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player has money in the Field (3, 4, 9, 10 and 11 pay 1:1). The shooter rolls a 4. How much does the dealer pay?',NULL,'1','A Field roll of 3, 4, 9, 10 or 11 pays even money (1:1).','craps_field',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player bets the Field (pays 1:1 on 3, 4, 9, 10 and 11). The roll is Yo — eleven. Calculate the payout.',NULL,'1','Eleven is a single Field number — the Field bet is paid at 1:1.','craps_field',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Field bet — the shooter rolls Aces (2). The Field pays double (2:1) on the 2. How much does the dealer pay?',NULL,'2','The 2 doubles the Field: the bet is paid at 2 to 1.','craps_field',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Field bet — Boxcars! The 12 pays double (2:1) in the Field. Calculate the payout.',NULL,'2','The 12 doubles the Field: the bet is paid at 2 to 1.','craps_field',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player bought the 4 (Buy bets pay true odds 2:1; the 5% vig was collected separately). The shooter rolls a 4. How much does the dealer pay?',NULL,'2','A Buy bet on the 4 pays true odds of 2:1 — the 5% commission is handled separately.','craps_place',FALSE,1,10,TRUE);

-- ─── Medium (difficulty 2) ───────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
((SELECT id FROM public.games WHERE name='Craps'),'payout','The point is 4. Player took odds behind the Pass Line (odds on the 4 pay 2:1). The shooter makes the point — calculate the payout on the odds bet.',NULL,'2','Odds on a point of 4 or 10 are paid at 2 to 1.','craps_odds',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','The point is 10 and the shooter rolls it. Player''s odds bet behind the Pass Line pays 2:1 on the 10. How much does the dealer pay on the odds?',NULL,'2','Odds on a point of 4 or 10 pay 2 to 1 — for every $1 taken the payoff is $2.','craps_odds',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','The point is 5. Odds taken on the 5 pay 3:2. The shooter makes the point — calculate the payout on the odds bet.',NULL,'1.5','Odds on a point of 5 or 9 are paid at 3 to 2 — for every $2 taken the payoff is $3.','craps_odds',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','The point is 9 and the shooter rolls a 9. The odds bet pays 3:2 on the 9. How much does the dealer pay on the odds?',NULL,'1.5','Odds on 5 and 9 pay 3 to 2.','craps_odds',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player bought the 10 (pays true odds 2:1, vig paid separately). The shooter rolls a 10. Calculate the payout.',NULL,'2','Buy bets on the 4 and 10 pay true odds of 2:1 after the 5% commission.','craps_place',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player has a Buy bet on the 5 (pays true odds 3:2, vig collected up front). The 5 rolls. How much does the dealer pay?',NULL,'1.5','Buy bets on the 5 and 9 pay true odds of 3:2 after the 5% commission.','craps_place',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player placed the 4 (Place bets on the 4 pay 9:5). The shooter rolls a 4. How much does the dealer pay?',NULL,'1.8','Place bets on the 4 and 10 pay 9 to 5 — divide the bet by 5 and multiply by 9.','craps_place',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player placed the 9 (Place bets on the 9 pay 7:5). The 9 rolls before a seven. Calculate the payout.',NULL,'1.4','Place bets on the 5 and 9 pay 7 to 5 — divide the bet by 5 and multiply by 7.','craps_place',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','One-roll prop: player is on Any Seven (pays 4:1). The shooter throws a 7. How much does the dealer pay?',NULL,'4','Any Seven wins on a total of 7 and pays 4 to 1.','craps_prop',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player throws in a bet on Any Craps (pays 7:1). The roll is a 3. Calculate the payout.',NULL,'7','Any Craps wins on 2, 3 or 12 and pays 7 to 1.','craps_prop',FALSE,2,10,TRUE);

-- ─── Hard (difficulty 3) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player is on the Yo — Eleven (pays 15:1). The shooter rolls 6-5. How much does the dealer pay?',NULL,'15','Eleven (Yo) is a one-roll prop paid at 15 to 1.','craps_prop',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','One-roll bet on Ace-Deuce — Craps three (pays 15:1). The dice land 1-2. Calculate the payout.',NULL,'15','Craps 3 (Ace-Deuce) pays 15 to 1.','craps_prop',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player bets the Aces — Snake Eyes (pays 30:1). Both dice show one spot up. How much does the dealer pay?',NULL,'30','Craps 2 (Aces / Snake Eyes) pays 30 to 1.','craps_prop',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','One-roll bet on Craps Twelve — Boxcars (pays 30:1). Two sixes roll. Calculate the payout.',NULL,'30','Craps 12 (Boxcars) pays 30 to 1.','craps_prop',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player has the 4 the Hardway (pays 7:1). The dice land 2-2 before an easy 4 or a seven-out. How much does the dealer pay?',NULL,'7','Hard 4 and Hard 10 pay 7 to 1.','craps_hardway',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Hard 10 (pays 7:1) — the shooter rolls 5-5. Calculate the payout on the Hardway bet.',NULL,'7','Hard 4 and Hard 10 pay 7 to 1.','craps_hardway',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Player has the Hard 6 (pays 9:1). The dice land 3-3. How much does the dealer pay?',NULL,'9','Hard 6 and Hard 8 pay 9 to 1.','craps_hardway',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Hard 8 (pays 9:1) — the shooter throws 4-4. Calculate the payout on the Hardway bet.',NULL,'9','Hard 6 and Hard 8 pay 9 to 1.','craps_hardway',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Hop bet on 3-3 (a pair hopping pays 30:1). The dice land 3-3. How much does the dealer pay?',NULL,'30','Any hardway (pair) bet as a Hop bet pays 30 to 1.','craps_prop',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Craps'),'payout','Hop bet on 5-4 (non-pair combinations hopping pay 15:1). The dice land 5-4. Calculate the payout.',NULL,'15','All non-pair Hop combinations pay 15 to 1.','craps_prop',FALSE,3,10,TRUE);


-- ============================================================
-- ============================================================
-- CRAPS — SHARED PROCEDURE QUESTIONS (30)
--   game_id NULL · is_procedure TRUE · category 'craps_procedure'
-- ============================================================
-- ============================================================

-- ─── Easy (difficulty 1) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
(NULL,'multiple_choice','How many Dealers make up a full Craps crew?','["Four — three working the game and one on break","Three — a stickman and two base dealers only","Two — one per end of the table","Five — one per player position"]','Four — three working the game and one on break','Four Dealers are assigned to a single Craps game; at any time three are working and the fourth is on break.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','Which position carries the primary responsibility for the conduct and pace of a Craps game?','["The Stickman","The Boxman","The base dealer on second base","The Pit Manager"]','The Stickman','The Stickman carries the primary responsibility for the conduct and pace of the game.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','How many dice must be present in the set at a Craps table during the game?','["Five","Two","Three","Six"]','Five','A set of five dice shall be present at the Craps table; the shooter selects and retains two.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','Who should set up proposition bets?','["Only the Stickperson","Any base dealer","The Boxman","The player making the bet"]','Only the Stickperson','All Dealers may book proposition bets, but only the Stickperson should set them up.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','What must a player have to qualify to shoot the dice?','["A Pass Line or Don''t Pass bet of at least the table minimum","Any bet anywhere on the layout","A Field bet","At least $100 in the rail"]','A Pass Line or Don''t Pass bet of at least the table minimum','To qualify to shoot, a player must have a Pass Line or Don''t Pass bet, and at least the table minimum must be wagered.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','Are verbal ''call bets'' accepted on the Craps game?','["No — absolutely no call bets will be accepted","Yes, if the Boxman hears the bet","Yes, for amounts under $25","Only on proposition bets"]','No — absolutely no call bets will be accepted','The procedures state that absolutely no call bets will be accepted.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','What is ''hawking'' the dice, which is strictly prohibited for base dealers?','["Following the dice with your eyes to the other end instead of watching your own end","Calling the dice before they stop","Touching the dice with your hand","Sliding the dice to the shooter"]','Following the dice with your eyes to the other end instead of watching your own end','Hawking — watching the dice travel to the opposite side of the table instead of your own end — is strictly prohibited.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','How must the shooter throw the dice?','["Both dice leave one hand simultaneously and roll down to strike the far end of the table","Any way the shooter likes, as long as both dice stay on the table","One die at a time, aimed at the stickman","Underhand, using both hands together"]','Both dice leave one hand simultaneously and roll down to strike the far end of the table','The dice must leave the shooter''s hand simultaneously, thrown with one hand, and roll down the table toward the far end — no lofting, sliding or spinning.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','In which direction does the opportunity to shoot the dice pass around the table?','["Clockwise, starting with the player immediately to the left of the Boxman","Counter-clockwise from the stickman","To whoever has the largest Pass Line bet","Randomly, at the Boxman''s discretion"]','Clockwise, starting with the player immediately to the left of the Boxman','The dice are offered to each customer in rotation clockwise around the table, beginning to the left of the Boxman.','craps_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','When may the Stickman call the total of the dice?','["Only after both dice have come to a complete stop","While the dice are still rolling, to speed up the game","After the base dealer confirms the number","Once the Boxman nods"]','Only after both dice have come to a complete stop','The Stickman may call dice only after they have come to a complete stop, and the total must be called before anyone touches them.','craps_procedure',TRUE,1,10,TRUE);

-- ─── Medium (difficulty 2) ───────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
(NULL,'multiple_choice','One die lands leaning against a player''s chips (a ''cocked die''). How is it called?','["By the high or uppermost side, opposite the object it rests against","It is automatically ''no roll''","The shooter chooses which side counts","The Boxman spins it flat and reads the result"]','By the high or uppermost side, opposite the object it rests against','A cocked die is called according to the high or uppermost side, and the total must be called before the dice are moved.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','One or both dice come to rest on money lying on the layout. What is the call?','["It is ''dice'' — the roll counts and is called","''No roll'' — the throw is void","The roll counts only if the Boxman agrees","The dice must be re-thrown from the same spot"]','It is ''dice'' — the roll counts and is called','If one or both dice stop on money on the layout, it is ''dice'' and will be called.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','One die comes to rest on top of the other. What is the call?','["''No roll''","The bottom die counts","The top die counts","Both dice are read as they lie"]','''No roll''','If the dice stop with one on top of the other, it is ''no roll''.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','When must the dice be checked before further use?','["When they go off the table, leave the Stickman''s clear sight, pass hand-to-hand between customers, or are suspect","Only when a player requests it","Once per hour on a schedule","Only after a winning prop bet"]','When they go off the table, leave the Stickman''s clear sight, pass hand-to-hand between customers, or are suspect','Dice must be checked when they leave the table, leave the Stickman''s sight, pass from one customer''s hands to another, or whenever a die is suspect.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','A die goes off the table. What options does the shooter have?','["Choose from the dice left in the bowl, or request the same die back after the Boxman checks it","Continue immediately with the same die, unchecked","Take any die from another table","The shooter loses the dice automatically"]','Choose from the dice left in the bowl, or request the same die back after the Boxman checks it','The player may choose from the remaining dice in the bowl and may request the same dice, but the Boxman must check them before they return to play.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','The shooter has a Don''t Pass bet and is reluctant to accept the point just rolled. What may they do?','["Reduce the Don''t Pass bet to the table minimum — once reduced it cannot be increased","Remove the Don''t Pass bet entirely and keep shooting","Move the bet to the Pass Line","Pass the dice but keep the bet at full value"]','Reduce the Don''t Pass bet to the table minimum — once reduced it cannot be increased','A reluctant Don''t Pass shooter may reduce the bet to the table minimum; at least the minimum must stay up to shoot, and the wager cannot be increased again.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','Where does a Dealer cut out change, and how is it delivered to the player?','["Cut out in the Come area with the inside hand, handed off with the outside hand to the apron — never into the player''s hand","Cut out on the Come numbers and handed directly to the player","Cut out anywhere convenient and placed in the betting area","Passed to the Stickman, who delivers it"]','Cut out in the Come area with the inside hand, handed off with the outside hand to the apron — never into the player''s hand','Change is cut out in the Come using the inside hand, handed off with the outside hand, and may never pass directly into a player''s hand. Change may never be cut out on the Come numbers.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','During a color change, what does the Dealer wait for before sending the higher-denomination chips out?','["The Box person verifies the amount and says ''Send it''","The player counts the chips and agrees","The Stickman taps the stack with the stick","Nothing — send it as soon as it is cut out"]','The Box person verifies the amount and says ''Send it''','On a color change the Box person cuts down the incoming chips, the Dealer cuts out the change on the Come, and the Box person verifies the amount and says ''Send it'' before it is handed off.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','How high are stacks cut when proving $1, $5, $100 and $1,000 cheques?','["Five high, with no more than 20 cheques in a row","Four high, with no more than 12 in a row","Ten high, in two rows","Any height, as long as the Boxman can see them"]','Five high, with no more than 20 cheques in a row','$1, $5, $100 and $1,000 cheques are run down in stacks no greater than 5 high; $25, $500 and $5,000 cheques are cut 4 high — never more than 20 cheques in a row.','craps_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','What is the take-and-pay rule on a decision roll?','["Always take the house''s winning (losing players'') bets before paying the winners","Pay winners first so players are never kept waiting","Take and pay simultaneously with both hands","Pay the largest bet first regardless of position"]','Always take the house''s winning (losing players'') bets before paying the winners','Take-Pay: always take what the house has won before paying.','craps_procedure',TRUE,2,10,TRUE);

-- ─── Hard (difficulty 3) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
(NULL,'multiple_choice','In what order are Pass Line bets paid?','["From the outside in, paying the odds first and then the flat bet for each wager","From the inside out, flat bet first","In whatever order the Boxman directs","Largest wager first, then descending"]','From the outside in, paying the odds first and then the flat bet for each wager','Pass Line bets are paid from the outside in — pay the odds and then the flat bet for each individual wager, first bet with the outside hand.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','A proposition bet covering three combinations (a ''three-way'') must be booked in what units?','["Units of $3","Units of $5","Any amount the player throws in","Units of $4"]','Units of $3','Prop bets with two combinations (splits) can be any amount, but bets with three combinations must be booked in units of $3.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','In what units must Horn and Horn High bets be booked?','["Horn bets in units of $4 or $5; Horn High bets in units of $5","Both in units of $4","Both in any amount","Horn in $5 units; Horn High in $4 units"]','Horn bets in units of $4 or $5; Horn High bets in units of $5','Horn bets must be booked in units of $4 or $5; Horn High bets must be booked in units of $5.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','On any sizable payoff (proposition, odds or place bet), what must the Dealer do?','["Call out the amount being paid so the Boxman can catch any error before the payoff is completed","Complete the payoff quickly and quietly","Wait for the player to confirm the math","Hand the payoff directly to the player"]','Call out the amount being paid so the Boxman can catch any error before the payoff is completed','On any sizable payoff the Dealer must call out the amount so the Boxman can catch errors; the payoff is cut out where the Boxman can see it and moved to the apron — never handed to the player.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','A player leaves the table with a bet still up, and nobody claims it after it is paid. How is this ''sleeper'' handled?','["Notify the Manager — it is house money until claimed and may never be taken as a toke","The crew may split it as a tip","It is pushed to the nearest player","It is locked up immediately as house winnings"]','Notify the Manager — it is house money until claimed and may never be taken as a toke','Sleeper bets and unclaimed money are considered house money until claimed; appropriating them as a toke is considered dishonesty.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','When may a $100 chip or higher be placed in the Craps toke box?','["Only with the approval of the Shift Manager on duty","Whenever a player tips it","Never, under any circumstances","Only on a dead game"]','Only with the approval of the Shift Manager on duty','$100 chips or higher will not be placed in the toke box unless approved by the Shift Manager on duty.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','When must a Craps Dealer clear their hands (clap once, palms shown up and down)?','["After every transaction, before touching any part of the body, and when being relieved","Only when leaving the pit","Once at the start of each shift","Only when the Boxman requests it"]','After every transaction, before touching any part of the body, and when being relieved','Dealers must clear their hands after every transaction, before touching any part of the body, and when being relieved.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','When may the Stickman be relieved?','["Only while the dice are in the ''box'' position with all work for the last roll complete — after identifying the shooter to the relief","At any time between rolls","Whenever the relief arrives, immediately","Only at the top of the hour"]','Only while the dice are in the ''box'' position with all work for the last roll complete — after identifying the shooter to the relief','The Stickman can only be relieved while the dice are in the box position after all work is complete, and must identify the shooter and pass on pertinent information to the incoming Stickman.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','What are the requirements for a Buy bet?','["Minimum $20, identified by a lammer, with the 5% vig rounded down to the nearest whole dollar","Minimum $10 with no commission","Any amount, marked with an ''ON'' button","Minimum $25 with the vig rounded up"]','Minimum $20, identified by a lammer, with the 5% vig rounded down to the nearest whole dollar','Buy bets must be a minimum of $20, are identified by a lammer, and all commissions are rounded down to the nearest whole dollar; the vig is returned if the bet is removed before a decision.','craps_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','A bet over the table maximum is not noticed until a decisive roll. What happens?','["Pay or take only up to the table maximum and return any overage to the player","The entire bet plays as wagered","The entire bet is void","The overage is kept by the house"]','Pay or take only up to the table maximum and return any overage to the player','If a bet over the table maximum reaches a decisive roll, only the table maximum is paid or taken; if it loses, the overage must be returned to the player.','craps_procedure',TRUE,3,10,TRUE);


-- ============================================================
-- ============================================================
-- CARIBBEAN STUD POKER — PAYOUT DRILLS (30) — odds in question
-- ============================================================
-- ============================================================

-- ─── Easy (difficulty 1) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The dealer qualifies and the player''s hand wins. The Ante pays even money (1:1). How much does the dealer pay on the Ante?',NULL,'1','A winning Ante is always paid at 1 to 1.','csp_ante',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player beats the dealer''s qualifying hand. Calculate the payout on the Ante (pays 1:1).',NULL,'1','The Ante pays even money when the player beats the dealer.','csp_ante',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The dealer cannot open — no Ace/King. Dealer calls ''no hand'' and pays the Ante only (1:1). How much does the dealer pay?',NULL,'1','When the dealer does not qualify, only the Ante is paid, at even money; the Bet pushes.','csp_ante',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Dealer does not qualify: the Bet pushes and the Ante is paid at 1:1. Calculate the Ante payout.',NULL,'1','A non-qualifying dealer pays even money on the Ante only.','csp_ante',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player calls and wins with one Pair (the Bet pays 1:1 on a Pair). How much does the dealer pay on the Bet?',NULL,'1','One Pair pays even money (1:1) on the Bet.','csp_bet',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: a Pair, which pays even money (1:1) on the Bet. Calculate the Bet payout.',NULL,'1','A Pair on the Bet pays 1 to 1.','csp_bet',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The player''s Pair beats the dealer''s qualifying hand. The Bet bonus for a Pair is 1:1 — how much is paid?',NULL,'1','The Bet bonus schedule starts at even money for one Pair.','csp_bet',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with Two Pair (the Bet pays 2:1). How much does the dealer pay on the Bet?',NULL,'2','Two Pair pays 2 to 1 on the Bet, up to the table maximum.','csp_bet',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: Two Pair, which pays 2:1 on the Bet. Calculate the payout.',NULL,'2','Two Pair pays 2 to 1 on the Bet.','csp_bet',FALSE,1,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The player''s Two Pair beats the dealer. At 2:1, what does the Bet pay?',NULL,'2','Two Pair is paid at 2 to 1 on the Bet.','csp_bet',FALSE,1,10,TRUE);

-- ─── Medium (difficulty 2) ───────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with Three of a Kind (the Bet pays 3:1). Calculate the Bet payout.',NULL,'3','Three of a Kind pays 3 to 1 on the Bet.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: trips — Three of a Kind pays 3:1 on the Bet. How much does the dealer pay?',NULL,'3','Three of a Kind is paid at 3 to 1 on the Bet, up to the table maximum.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The player''s Three of a Kind beats the dealer''s hand. At 3:1, calculate the payout on the Bet.',NULL,'3','Trips pay 3 to 1 on the Bet.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with a Straight (the Bet pays 4:1). How much does the dealer pay on the Bet?',NULL,'4','A Straight pays 4 to 1 on the Bet.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: a Straight, paying 4:1 on the Bet. Calculate the payout.',NULL,'4','A Straight is paid at 4 to 1 on the Bet, up to the table maximum.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The player''s Straight beats the dealer. At 4:1, what does the Bet pay?',NULL,'4','A Straight pays 4 to 1 on the Bet.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with a Flush (the Bet pays 5:1). Calculate the Bet payout.',NULL,'5','A Flush pays 5 to 1 on the Bet.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: a Flush at 5:1 on the Bet. How much does the dealer pay?',NULL,'5','A Flush is paid at 5 to 1 on the Bet, up to the table maximum.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with a Full House (the Bet pays 7:1). Calculate the payout on the Bet.',NULL,'7','A Full House pays 7 to 1 on the Bet.','csp_bet',FALSE,2,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: Full House, paying 7:1 on the Bet. How much does the dealer pay?',NULL,'7','A Full House is paid at 7 to 1 on the Bet, up to the table maximum.','csp_bet',FALSE,2,10,TRUE);

-- ─── Hard (difficulty 3) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The player''s Full House beats the dealer''s qualifying hand. At 7:1, calculate the Bet payout.',NULL,'7','A Full House pays 7 to 1 on the Bet.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with Four of a Kind (pays 20:1 on the Bet). Calculate the full 20:1 payout before applying the $1,000 table cap.',NULL,'20','Four of a Kind pays 20 to 1 on the Bet; in live play the total payout is capped at the $1,000 table maximum.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: Four of a Kind at 20:1. Before the table cap, how much would the Bet pay?',NULL,'20','Quads pay 20 to 1, up to the $1,000 table maximum.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The player''s quads beat the dealer. Calculate the 20:1 Bet payout (payouts are capped at $1,000 in live play).',NULL,'20','Four of a Kind pays 20 to 1 on the Bet, capped at the table maximum.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with a Straight Flush (pays 50:1 on the Bet). Calculate the full 50:1 payout before the $1,000 cap.',NULL,'50','A Straight Flush pays 50 to 1 on the Bet; the cards must also be sent to Surveillance.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: a Straight Flush at 50:1. Before the table cap, what would the Bet pay?',NULL,'50','A Straight Flush is paid at 50 to 1, capped at the $1,000 table maximum in live play.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','A Straight Flush beats the dealer''s hand. Calculate the 50:1 Bet payout (capped at $1,000 in live play).',NULL,'50','A Straight Flush pays 50 to 1 on the Bet.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Player wins with a Royal Flush (pays 100:1 on the Bet). Calculate the full 100:1 payout before the $1,000 cap.',NULL,'100','A Royal Flush pays 100 to 1 on the Bet, capped at the table maximum; the decks go to Surveillance.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','Winning hand: a Royal Flush at 100:1. Before the table cap, what would the Bet pay?',NULL,'100','A Royal Flush is paid at 100 to 1 on the Bet.','csp_bet',FALSE,3,10,TRUE),
((SELECT id FROM public.games WHERE name='Caribbean Stud Poker'),'payout','The player''s Royal Flush beats the dealer. Calculate the 100:1 Bet payout (capped at $1,000 in live play).',NULL,'100','A Royal Flush pays 100 to 1 on the Bet, capped at the $1,000 table maximum.','csp_bet',FALSE,3,10,TRUE);


-- ============================================================
-- ============================================================
-- CARIBBEAN STUD POKER — SHARED PROCEDURE QUESTIONS (30)
--   game_id NULL · is_procedure TRUE
--   category 'caribbean_stud_procedure'
-- ============================================================
-- ============================================================

-- ─── Easy (difficulty 1) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
(NULL,'multiple_choice','What minimum hand must the dealer have to qualify (open) in Caribbean Stud Poker?','["At least Ace/King or higher","At least one Pair","Any Ace","Queen high or better"]','At least Ace/King or higher','The dealer must have a hand of at least an Ace/King or higher to qualify; otherwise the dealer calls ''no hand''.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','How are the cards dealt in Caribbean Stud Poker?','["Five cards face down to each player and the dealer, with the dealer''s last card turned face up","Five cards face up to everyone","Two cards down and three up, like stud","Seven cards to each player"]','Five cards face down to each player and the dealer, with the dealer''s last card turned face up','The Dealer deals five cards to each player and to him/herself face down, except the Dealer''s last card, which is turned face up.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','How does a player join the progressive jackpot?','["By placing $1 on the red circle above the Ante before the lock-out","By doubling their Ante","By telling the dealer verbally","By placing $5 in the betting circle"]','By placing $1 on the red circle above the Ante before the lock-out','A player wishing to participate in the progressive wagers $1 on the red circle above the Ante; the red light confirms the bet.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','How much must a player wager to ''call'' the dealer''s hand?','["Exactly twice the amount of their Ante","The same amount as their Ante","Any amount up to the table maximum","Half of their Ante"]','Exactly twice the amount of their Ante','To call and stay in the game, the player must make an additional bet of exactly twice the amount of the Ante.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','The dealer does not qualify. What is paid to players who called?','["Even money on the Ante only — the Bet is a push","Both the Ante and the Bet at even money","Nothing — all bets push","The Bet only"]','Even money on the Ante only — the Bet is a push','If the dealer''s hand does not contain at least Ace/King, the dealer calls ''no hand'' and pays even money on the Ante only.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','Player and dealer hold completely identical hands. What happens?','["It is a push — no action on the hand","The player wins automatically","The dealer wins automatically","The Ante is paid but the Bet loses"]','It is a push — no action on the hand','A tie hand between player and dealer constitutes no action and is a push; only a higher 3rd, 4th or 5th card breaks a tie.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','Does cash (currency) ever play as a bet in Caribbean Stud Poker?','["No — money does not play under any circumstances","Yes, if under $100","Yes, with Manager approval","Only on the progressive"]','No — money does not play under any circumstances','The procedures state plainly that money (cash) does not play under any circumstances.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','Which button does the dealer press before dealing to stop further progressive bets?','["The lock-out button","The reset button","The green shuffle button","The payout key"]','The lock-out button','Before dealing, the dealer presses the lock-out button to restrict further betting on the progressive jackpot.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','Which button does the dealer press after each hand so players can bet the progressive again?','["The reset button","The lock-out button","The payoff key","The service button"]','The reset button','At the completion of each hand the dealer presses the reset button, allowing players to bet on the progressive jackpot again.','caribbean_stud_procedure',TRUE,1,10,TRUE),
(NULL,'multiple_choice','What may the dealer never do with currency or chips?','["Give them to or take them from a player''s hand","Count them on the layout","Spread them for surveillance","Announce the amount out loud"]','Give them to or take them from a player''s hand','Never give or take currency or chips from a player''s hand — all transactions are completed on the layout in public view.','caribbean_stud_procedure',TRUE,1,10,TRUE);

-- ─── Medium (difficulty 2) ───────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
(NULL,'multiple_choice','When must a Caribbean Stud dealer call out ''checks play''?','["When dealing to any bet of $100 or more","On every winning bet","Only on progressive wins","When a player buys in with cash"]','When dealing to any bet of $100 or more','When dealing to any bet of $100 or more, the Dealer must call ''checks play'' so the table manager is aware of the action.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','A player makes a Straight Flush or Royal Flush. What happens to the cards?','["The decks are delivered to Surveillance","They are shuffled back in and play continues","They are framed for display","They are dropped in the drop box"]','The decks are delivered to Surveillance','With any Straight Flush and up, the cards must be sent to Surveillance.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','A player shows Four of a Kind or better with a progressive bet. What must happen before the payout?','["Surveillance is called to verify the hand and the Manager approves the payout","The dealer pays immediately to keep the game moving","The player signs a receipt","The cards are reshuffled first"]','Surveillance is called to verify the hand and the Manager approves the payout','For 4 of a Kind and up, Surveillance must verify that everything is correct and the Manager must approve before the payout is made; new decks are then placed in the game.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','When does Surveillance receive all cards from a table?','["When the table has a significant win or loss greater than $10,000 in a shift","At the end of every shift","Whenever a deck is a month old","Only when a player complains"]','When the table has a significant win or loss greater than $10,000 in a shift','Surveillance receives all cards from any table that incurs a significant win or loss of greater than $10,000 in any shift.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','How must the dealer place the cards for spots 1 and 2?','["With the left hand only","With the right hand only","With both hands together","By sliding them across the layout"]','With the left hand only','The Dealer places the cards for spot number 1 and 2 with the left hand only.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','A player folds. What does the dealer do?','["Collect the Ante and the cards, spread and count them, then place them in the discard rack","Return the Ante and take the cards","Leave the cards until the hand is over","Collect the Ante and leave the cards face down"]','Collect the Ante and the cards, spread and count them, then place them in the discard rack','When a player folds, the dealer collects the cards and the Ante, spreads and counts the cards, then places them into the discard rack.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','Two of the dealer''s cards are exposed during the deal. What is the ruling?','["It is a misdeal","The game continues normally","Only the dealer''s hand is void","The exposed cards become the face-up cards"]','It is a misdeal','An exposed player card does not constitute a misdeal, but if two of the dealer''s cards are exposed it is a misdeal.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','A player is dealt an incorrect number of cards. What is the ruling?','["All hands are void and the cards are reshuffled","Only that player''s hand is void","The dealer deals replacement cards","The player plays the cards dealt"]','All hands are void and the cards are reshuffled','If any player or the dealer is dealt an incorrect number of cards, all hands shall be voided and the cards reshuffled.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','In what order does the dealer compare, pay and take hands?','["From right to left","From left to right","Highest bet first","Progressive players first"]','From right to left','The dealer compares, pays and takes from right to left.','caribbean_stud_procedure',TRUE,2,10,TRUE),
(NULL,'multiple_choice','May the dealer total the Bet and the Ante into a single payout?','["No — pay the Ante by sizing into the bet; do not total them","Yes, to speed up the game","Yes, but only under $100","Only when the Manager is watching"]','No — pay the Ante by sizing into the bet; do not total them','General rules: pay the Ante by sizing into the bet for speed and accuracy, and do not total the Bet and Ante.','caribbean_stud_procedure',TRUE,2,10,TRUE);

-- ─── Hard (difficulty 3) ─────────────────────────────────────
INSERT INTO public.questions (game_id,type,question_text,options,correct_answer,explanation,category,is_procedure,difficulty,points,is_active)
VALUES
(NULL,'multiple_choice','Under the progressive jackpot schedule, what does a Straight pay?','["$25","$50","$100","$500"]','$25','Progressive payoffs: Royal Flush 100%, Straight Flush 10%, Four of a Kind $500, Full House $100, Flush $50, Straight $25.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','Two or more players qualify for the progressive jackpot on the same hand. Who is paid first?','["The lowest-value hand first, progressing to the highest","The highest-value hand first","The player closest to the dealer","They are paid simultaneously"]','The lowest-value hand first, progressing to the highest','When multiple players qualify on the same deal, pay the lowest value hands first, progressing to the highest, reducing the progressive amount after each payout.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','Two players make a Royal Flush on the same deal. How is the 100% jackpot handled?','["The winners share the jackpot as an aggregate","The first player dealt takes it all","Each is paid 100% of the jackpot","The jackpot rolls over to the next hand"]','The winners share the jackpot as an aggregate','If two or more players qualify for all or part of the progressive jackpot during the same hand, the winners share the jackpot as an aggregate.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','The dealer does not qualify, but a player holds a progressive-qualifying hand. What is paid?','["The Ante and the progressive — NOT the Bet to call the dealer","Nothing until the next qualifying hand","The Bet and the progressive","Only the progressive"]','The Ante and the progressive — NOT the Bet to call the dealer','If the dealer does not have a qualifying hand, players with progressive-qualifying hands are paid the Ante and the progressive, but not the Bet.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','What are the Caribbean Stud wagering limits?','["Ante up to $250, Bet up to $500, all payouts capped at the $1,000 table limit","Ante up to $500, Bet up to $1,000, no payout cap","Ante and Bet both up to $1,000","Ante up to $100, Bet up to $200, payouts capped at $500"]','Ante up to $250, Bet up to $500, all payouts capped at the $1,000 table limit','The limit on the Ante is up to $250, the limit on the Bet is $500, and all payouts are up to the $1,000 table limit.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','Which chips may go into the toke box without a Manager''s color change?','["Only checks of $25 or less","Any denomination","Checks up to $100","Only $1 and $5 checks"]','Only checks of $25 or less','No checks over $25 will be placed in the toke box; a Manager authorizes any necessary color change first.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','At closing, who is allowed to drop the Closer slip?','["Only the dealer, unless two table Managers conduct the count","Any Manager","The Security Officer","The cashier"]','Only the dealer, unless two table Managers conduct the count','Only the dealer is allowed to drop the Closer slip, unless two table Managers conduct the count.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','Which denominations are run down in stacks no greater than four high?','["$2.50, $25, $500 and $5,000 cheques","$1, $5, $100 and $1,000 cheques","All denominations","Only $500 and above"]','$2.50, $25, $500 and $5,000 cheques','$2.50, $25, $500 and $5,000 cheques are cut four high; $1, $5, $100 and $1,000 cheques are cut five high — never more than 20 in a row.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','What must the dealer verify on a Marker before signing?','["Player''s name, game type, table number and amount — then sign with kronus number","Only the total amount","Only the player''s name and date","Nothing — the Manager verifies everything"]','Player''s name, game type, table number and amount — then sign with kronus number','The dealer must verify all information on the Marker (player''s name, game type, table number, amount) and sign with their kronus number.','caribbean_stud_procedure',TRUE,3,10,TRUE),
(NULL,'multiple_choice','A player who did NOT bet the progressive makes a Flush. How is the hand paid?','["Call a Manager and pay normal table odds with approval — not the progressive","Pay the progressive anyway as a courtesy","Pay nothing beyond the Ante","Let the player choose table odds or progressive"]','Call a Manager and pay normal table odds with approval — not the progressive','If the player is not participating in the progressive and makes a qualifying hand, a Manager is called and the payout is made at normal table odds, not the progressive odds.','caribbean_stud_procedure',TRUE,3,10,TRUE);
